- name: Check disk space
  hosts: all
  become: true

  tasks:
    - name: Check disk space on Linux
      block:
        - name: Check if the system is CentOS
          set_fact:
            is_centos: "{{ ansible_distribution | lower == 'centos' }}"
          ignore_errors: true
        - name: Check if the system is Ubuntu
          set_fact:
            is_ubuntu: "{{ ansible_distribution | lower == 'ubuntu' }}"
          ignore_errors: true
        - name: Check disk space on CentOS
          command: df -hT
          when: is_centos | bool
          register: centos_disk_space
        - name: Check disk space on Ubuntu
          command: df -hT
          when: is_ubuntu | bool
          register: ubuntu_disk_space
        - name: Print disk space on CentOS
          debug:
            msg: "{{ centos_disk_space.stdout_lines }}"
          when: is_centos | bool
        - name: Print disk space on Ubuntu
          debug:
            msg: "{{ ubuntu_disk_space.stdout_lines }}"
          when: is_ubuntu | bool
      when: "ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'"
    - name: Check disk space on Windows
      block:
        - name: Check disk space on Windows
          win_shell: Get-Volume | Select-Object -Property DriveLetter, FileSystemLabel, FileSystem, SizeRemaining, Size | ConvertTo-Csv -NoTypeInformation
          register: windows_disk_space
        - name: Print disk space on Windows
          debug:
            msg: "{{ windows_disk_space.stdout_lines }}"
      when: ansible_os_family == 'Windows'
