---
- hosts: all
  
  become: yes
  become_user: root

  tasks:
    - name: List all ports
      ansible.builtin.debug:
        msg: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique | sort | list }}"
